management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: configprops, env
        
  endpoint:
    health: 
      show-details: always
  health:
    defaults:
      enabled: true
    db:
      enabled: true
      
spring:
  datasource:
    url: ${RDS_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml


usuario:
  client:
    url: ${USUARIO_URL:http://localhost:8081}
    
    